version: '2'

services:
    web:
        build:
          context: ./nginx
          dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./hansesim:/home/student/htdocs/hansesim
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./logs:/var/log/nginx
        networks:
            - hansesim
    php7:
        build:
          context: ./php-fpm
          dockerfile: Dockerfile
        volumes:
            - ./hansesim:/home/student/htdocs/hansesim
        networks:
            - hansesim
        ports:
            - "9001:9000"
        environment:
          XDEBUG_CONFIG: "remote_host=192.168.1.51"
          #ipconfig getifaddr en0
          PHP_IDE_CONFIG: "serverName=Test"

    db:
      image: mysql
      ports:
          - 3306:3306
      environment:
        MYSQL_DATABASE: hansedb
        MYSQL_USER: hanseuser
        MYSQL_PASSWORD: hansepassword
        MYSQL_ROOT_PASSWORD: hansepassword
      networks:
          - hansesim
networks:
    hansesim:
        driver: bridge
